#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
header="\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s|listen 80 default_server;|&$header|g" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
errorp="\n\terror_page 404 /404.html;"
sed -i "s|listen 80 default_server;|&$errorp|g" /etc/nginx/sites-available/default
sudo service nginx restart
