#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
header="\n\tadd_header X-Served-By '$HOSTNAME';"
sed -i "s/listen 80 default_server;/&$header/g" /etc/nginx/sites-available/default
sudo service nginx restart
