#!/usr/bin/env bash                                                           
# Install and configure HAproxy on your lb-01 server                          
balancer="\                                                                   
frontend haproxy_balancer                                                     
    bind *:80                                                                 
    mode http                                                                 
    default_backend webservers                                                
                                                                              
backend webservers                                                            
    balance roundrobin                                                        
    server 971-web-01 35.227.5.245:80 check                                   
    server 971-web-02 3.236.14.41:80 check                                    
"                                                                             
apt-get -y install software-properties-common                                 
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8                            
sudo apt-get -y update                                                        
sudo apt-get -y install haproxy=1.8.\*                                        
echo "$balancer" >> /etc/haproxy/haproxy.cfg                                  
sudo service haproxy restart
