#!/usr/bin/env bash
# Script that displays Holberton School 10 times,  but for the 9th iteration, displays Holberton School and then Hi on a new line
i=0
while [ $i -le 9 ]
do
	echo "Holberton School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	((i++))
done

