#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
i=0
while [ $i -le 12 ];
do
	echo "Hour: $i"
	min=1
	while [ $min -le 59 ];
	do
		echo "$min"
		((min++))
	done
	((i++))
done
