#!/usr/bin/env bash
# Bash script that gives you information about the school file
file="school"
if [ -e "$file" ];
then
	echo "school file exists"
	if [ -f "$file" ];
	then
		echo "school is a regular file"
	fi
	if [ -s "$file" ];
	then
		echo "school file is not empty"
	else
		echo "school is empty"
	fi
else
	echo "school file does not exist"
fi
