#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file
file="holbertonschool"
if [ -e "$file" ];
then
	echo "holbertonschool file exists"
	if [ -f "$file" ];
	then
		echo "holbertonschool is a regular file"
	fi
	if [ -s "$file" ];
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool is empty"
	fi
else
	echo "holbertonschool file does not exist"
fi
