#!/usr/bin/env bash
# Copy of #1 Nginx is running as the nginx user.
pkill -9 apache2
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx start
